### ISSUE TITLE
webmention.js: RSVPs do not display the actual RSVP

### ISSUE THREAD

**Issue by jamietanna** [PlaidWeb/webmention.js#1]
Although we see that the RSVP is there, we can't easily see within the output whether it's yes/no/maybe/etc - it'd be cool to have this represented!

Follow-up to #2 as we're now in business again.

**Comment by fluffy-critter** [comment]
Okay, I added that functionality in pull request #2. Feel free to weigh in on it! In particular I'm not so sure about the "maybe" emoji.

**Comment by jamietanna** [comment]
Awesome, I'll look at trying this locally and see how it looks.

~We could always use ie 🤷‍♀️ or 🤔 for `maybe`?~
