### ISSUE TITLE
Add build/minify step

### ISSUE THREAD

**Issue by fluffy-critter** [PlaidWeb/webmention.js#10]
Following on from #9, if there's going to be npm packaging, might as well also add in a build/minification/test step.

**Comment by Ryuno-Ki** [comment]
Do you have preferred tooling?
Something like
- Grunt
- Gulp
- Webpack
- Parcel
- Rollup

Or can we go plain npm run-scripts?
For JS minification, use terser. It's the successor of uglify-js.

I can fill a PR if you want.
Just need to know, whether you have prior experience with some of the tooling.

**Comment by fluffy-critter** [comment]
I'm pretty apathetic to the specific tooling, as I do not live in the JavaScript packaging universe, I just occasionally glance blows with it. Just keep it simple, y'know?

I mean I usually just use a Makefile for this sort of thing.

**Comment by Ryuno-Ki** [comment]
But you have „Web” in this org :o

Just kidding. Find JS part in #11.

**Comment by fluffy-critter** [comment]
Fixed in #11. Thanks!

**Comment by fluffy-critter** [comment]
> But you have „Web” in this org :o

Didn't you hear? Server-side rendering is the future! Google invented it and everything. ;)

**Comment by Ryuno-Ki** [comment]
> Google invented it and everything.

Oh, yeah! Let's rewrite everything in Angular :-D

Glad that I could help :-)
