### ISSUE TITLE
Add demand loading of avatar images

### ISSUE THREAD

**Issue by fluffy-critter** [PlaidWeb/webmention.js#17]
Context: https://www.zachleat.com/web/facepile/

Relatedly, should add some mechanism for configuring a caching resize proxy (although that's hard to do securely in a client-side JS library in a way that avoids abuse, and the server-side component should probably lean on the webmention.io avatar cache)

**Comment by coliff** [comment]
As a quick, helpful partial solution it'd be great to add native lazy-loading of images with `loading="lazy"` on the img tag.

**Comment by fluffy-critter** [comment]
Ah, yeah, that'd probably be helpful too. I keep forgetting that's a thing now.

**Comment by coliff** [comment]
Yeah, it works great and is supported on all browsers now (except Safari, which I expect will follow soon since it's technically implemented but behind the experimental webkit features menu).

**Comment by fluffy-critter** [comment]
Yeah and your comment inspired me to finally add that on Publ as well, since it's easy enough :)

**Comment by fluffy-critter** [comment]
Fixed in #20
