### ISSUE TITLE
Modernize Javascript

### ISSUE THREAD

**Issue by fluffy-critter** [PlaidWeb/webmention.js#25]
1. A lot of strings can be simplified using template literals
2. There's no need for the fetch() polyfill anymore
3. It's probably safe to do native async/await on fetch()

**Comment by Ryuno-Ki** [comment]
I proposed #29 as a possible solution (note, that merging it won't close this issue).
`async`/`await` is not part of it.

**Comment by fluffy-critter** [comment]
Fixed in #32
