### ISSUE TITLE
Update README to include i18n

### ISSUE THREAD

**Issue by fluffy-critter** [PlaidWeb/webmention.js#26]
This got overlooked in #24, oops

**Comment by Ryuno-Ki** [comment]
Not overlooked, but I prefer small PRs :)

**Comment by fluffy-critter** [comment]
I prefer the docs to be up-to-date with the state of the code, is all.

**Comment by Ryuno-Ki** [comment]
Two commits, since I got the GFM syntax wrong at first attempt: https://www.pluralsight.com/guides/working-tables-github-markdown
