### ISSUE TITLE
Missing mapping of follow-up

### ISSUE THREAD

**Issue by Ryuno-Ki** [PlaidWeb/webmention.js#30]
Compare

https://github.com/PlaidWeb/webmention.js/blob/694cce41541c3d9ba49dd460d5baab75be09b8f3/static/webmention.js#L320-L327

with

https://github.com/PlaidWeb/webmention.js/blob/694cce41541c3d9ba49dd460d5baab75be09b8f3/static/webmention.js#L122-L140

and you'll notice, that `follow-up` isn't mapped.
On purpose?

**Comment by fluffy-critter** [comment]
Hm, yeah, it should probably go into `collects`.
