### ISSUE TITLE
Define error handling

### ISSUE THREAD

**Issue by Ryuno-Ki** [PlaidWeb/webmention.js#35]
In case there was an issue with webmention.io (think script blocker), there is no visual feedback right now.
Should it show a message at least?
(Would need to be translatable)

**Comment by fluffy-critter** [comment]
The failure mode is to just not show anything and this is by design. Webmention display is entirely optional.

**Comment by Ryuno-Ki** [comment]
Okay, so I'll add a comment in the source code, that this is intentional.
(And remove the rethrown error).
