### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by Ryuno-Ki** [PlaidWeb/webmention.js#36]
After #35, I feel like the code reached a new level to warrant another version to get pinned.
What do you think?

**Comment by fluffy-critter** [comment]
I already bumped it to 0.5.0 last night, because of the i18n addition.

**Comment by fluffy-critter** [comment]
Also IMO code structure doesn't warrant version changes, because that's all internal. User-visible functionality changes, and developer-visible API changes, warrant version changes.

**Comment by Ryuno-Ki** [comment]
Ah, I missed that version bump.
Okay, fine then :)
