### ISSUE TITLE
Default requires i18next?

### ISSUE THREAD

**Issue by nekr0z** [PlaidWeb/webmention.js#38]
`comments-are-reactions` is false by default, but without `i18next` the "Replies" header gets mangled (i.e. "+ t(Replies) +")

Wouldn't it be nice if defaults just worked without requiring additional setup?

**Comment by fluffy-critter** [comment]
That had nothing to do with i18next and was due to a partial conversion of a complex string expression into a template literal, which just got overlooked in testing. It is now fixed.

**Comment by Ryuno-Ki** [comment]
My bad :(
