### ISSUE TITLE
Mishandling of empty name string

### ISSUE THREAD

**Issue by aciccarello** [PlaidWeb/webmention.js#41]
I noticed that some reactions were coming through with a title of " liked". The author object was defined with empty string values 
json```{
  "type": "card",
  "name": "",
  "photo": "",
  "url": ""
}```

I believe the check for the author name should use an `||` operator rather than a nullish check.
https://github.com/PlaidWeb/webmention.js/blob/72e4372ced19eaed06f51e16f6e13b3de8dd14a2/static/webmention.js#L206

**Comment by fluffy-critter** [comment]
Ah, you're right. That's a pretty easy fix at least.
