### ISSUE TITLE
Reactions on new line

### ISSUE THREAD

**Issue by amino-8** [PlaidWeb/webmention.js#44]
Webmentions have become a breeze with your code so thank you!

I'm trying to figure out the code to make some changes for myself. One thing I'm looking for is how to remove the new line between the author image and the reaction. I think it might look cleaner on the same line. Can you point me in the direction of where I should be looking?
![Screenshot 2023-08-26 161548](https://github.com/PlaidWeb/webmention.js/assets/72126990/77b68999-82db-41e7-9e54-183bcd56887b)

**Comment by fluffy-critter** [comment]
That would be a function of the style sheet you're using. If you're using the provided .css file then it's likely there's another style rule on your site that's interfering with it. In particular make sure you don't have any `display:block` rules on the different image bits. Your browser's style inspector should help you track it down.

**Comment by amino-8** [comment]
Found it! Many thanks for pointing me in the right direction. It was indeed a display:block in the main stylesheet.
