### ISSUE TITLE
When not configured, don't set the request parameters

### ISSUE THREAD

**Issue by fluffy-critter** [PlaidWeb/webmention.js#8]
Per conversation on #7

**Comment by Ryuno-Ki** [comment]
Am I right in assuming, the subject refers to the GET parameters of

https://github.com/PlaidWeb/webmention.js/blob/1aff7d3daec51e17fbc7cabd6e68170c21b22d7b/static/webmention.js#L415-L419

for webmention.io? (`sortBy` / `sortDir` and `maxWebmentions`)

**Comment by fluffy-critter** [comment]
Yeah. It's a pretty minor thing, the intention is just that webmention.js should always use webmention.io's defaults instead of adding its own set of defaults that might be confusing, but it might be even more confusing to have every site using webmention.js have a change in behavior if webmention.io ever changes things. So I don't think this is a valid issue after all.
