### ISSUE TITLE
Add proper packaging, versioning

### ISSUE THREAD

**Issue by fluffy-critter** [PlaidWeb/webmention.js#9]
With more and more people using this, it would be helpful to provide semantic versioning in case people need to know about updates/bug fixes/etc.

And if things are going to be semantically versioned, might as well also make it available in npm to make it easier to manage for folks who use npm to manage their JS dependencies.

**Comment by Ryuno-Ki** [comment]
Since you have #11 merged now, you perhaps want to use [`npm version`](https://docs.npmjs.com/cli/version) for this.

In order to control, what goes to the NPM registry, use [`files` property of `package.json`](https://docs.npmjs.com/files/package.json#files).
